WebApp/Models/Apartment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models
{
    public class Apartment : Entity
    {        
        [DisplayName("Номер квартиры")]
        public int NumberOfApartment { get; set; }

        [DisplayName("Ссылка на сайт застройщика")]
        public string? Url { get; set; }

        [DisplayName("Текущая цена")]
        public double Price { get; set; }

        [DisplayName("Количество комнат")]
        public int Rooms { get;set; }

        [DisplayName("История цен")]
        [ForeignKey("ApartmentPriceHistory")]
        public virtual ICollection<ApartmentPriceHistory>? PriceHistory { get; set; }
        

    }
}

WebApp/Models/ApartmentPriceHistory.cs
namespace WebApp.Models
{
    public class ApartmentPriceHistory : Entity
    {        
        public int ApartmentId { get; set; }
        public DateTime PriceChangeDate { get; set; }

        public double PriceAtDate { get; set; }

    }
}

WebApp/Models/DataPoint.cs
namespace WebApp.Models
{
    public class DataPoint
    {
        public DateTime x { get; set; }
        public int y { get; set; }    
    }
}

WebApp/Models/Entity.cs
namespace WebApp.Models
{
    public abstract class Entity
    {  
        public int Id { get; set; }
    }
}

WebApp/Controllers/ApartmentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Text.Encodings.Web;
using System.Text.Json;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class ApartmentController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IService _service;       

        public ApartmentController(IConfiguration Configuration, IService service)
        {            
            _configuration = Configuration;
            _service = service;
        }
        // 
        // GET: /Apartment/
        public IActionResult Index(string sortOrder, string sortCol)
        {
            ViewBag.SortParam = string.IsNullOrWhiteSpace(sortOrder) ? "desc" : "";
            var whereString = !string.IsNullOrWhiteSpace(sortCol) ? $"order by {sortCol} {sortOrder}" : "";
            var apartments = GetApartments(whereString);          
            return View(apartments);
        }
        // 
        // GET: /Apartment/Filter
        public IActionResult Filter(string filterName, string filterValue)
        {
            var apartments = new List<Apartment>();
            if (!string.IsNullOrWhiteSpace(filterName))
            {
                var filterString = string.IsNullOrWhiteSpace(filterValue) ? "" : $"where {filterName} = '{filterValue}'";
                apartments = GetApartments(filterString);
            }
            return PartialView("Table", apartments);
        }

        private List<Apartment> GetApartments(string whereString)
        {
            try
            {                   
                var constr = _configuration.GetConnectionString("DefaultApartmentConnection");
                var aparmtnets = (List<Apartment>)_service.GetData(whereString, constr);
                GetChartData(aparmtnets);
                return aparmtnets;
            }
            catch (Exception)
            {
                //TODO: error handler/error logger
                return new List<Apartment>();
            }
        }
        private void GetChartData (List<Apartment> apartments)
        {
            var grouped = apartments.Where(x => x.PriceHistory != null).SelectMany(p => p.PriceHistory.Where(ph => ph.PriceChangeDate != DateTime.MinValue).GroupBy(d => d.PriceChangeDate.Date.Month).Select(c => new DataPoint
            {
                x = c.First().PriceChangeDate,
                y = (int)c.Average(p => p.PriceAtDate)
            })).ToList();
            ViewBag.ChartData = JsonSerializer.Serialize(grouped);
        }
    }
}

WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a class="nav-link text-dark" asp-area="" asp-controller="Apartment">Квартиры</a>
    
</div>

WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="nav-link text-dark" asp-area="" asp-controller="Apartment">Квартиры</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>    
    <script src="https://cdn.canvasjs.com/jquery.canvasjs.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Apartment/Index.cshtml
@model IEnumerable<WebApp.Models.Apartment>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Apartments";
    Layout = "~/Pages/Shared/_Layout.cshtml";
    
    
}

<h1>Apartments</h1>

<p>
	<div id="chartContainer" style="height: 370px; width: 80%;"></div>
</p>
<label for="SearchString">Количество комнат</label>
<input type="text" name="SearchString" value=""/>
<input type="submit" value="Поиск" class="btn search-filter btn-default" /> |
<a asp-action="Index">Вернуть весь список</a>
<div class="table">
    <partial name="Table" data="@Model">
</div>

WebApp/Views/Apartment/Table.cshtml
@using WebApp.Models;
@model IEnumerable<WebApp.Models.Apartment>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var dataPoints = string.IsNullOrWhiteSpace((string)ViewBag.ChartData) ? "" : (string)ViewBag.ChartData;
    
}

<div style="visibility:hidden" class="dataPoints" data-points="@dataPoints"></div>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.NumberOfApartment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                <a asp-action="Index" asp-route-sortCol="@("rooms")" asp-route-sortOrder="@(ViewBag.SortParam)">@Html.DisplayNameFor(model => model.Rooms)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceHistory)
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfApartment)
                </td>
                <td>
                    <a href="@Html.DisplayFor(modelItem => item.Url)">@Html.DisplayFor(modelItem => item.Url)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rooms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>

                <td>
                    @foreach (var ph in item.PriceHistory)
                    {
                        <p>
                            Дата: @(ph.PriceChangeDate.Date.ToShortDateString())
                            Цена: @ph.PriceAtDate
                        </p>

                    }
                </td>

                @* <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td> *@
            </tr>
        }
    </tbody>
</table>